# Generated by Django 4.0.4 on 2022-05-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Produit',
        ),
    ]
