# Generated by Django 4.0.4 on 2022-05-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_name_product_produit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Produit',
            new_name='name',
        ),
    ]
